# H2 conf to file in cp
spring:
  datasource:
    url: jdbc:h2:file:./spring-boot-h2-db
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    com.aname: debug
